version: 0.0
os: windows
files:
  - source: \Scripts\*
    destination: C:\temp\HelloWorldApp
  - source: \index.html
    destination: c:\inetpub\wwwroot
hooks:
  BeforeInstall:
    - location: \Scripts\before-install.bat
      timeout: 300
  AfterInstall:
    - location: \Scripts\after-install.bat
      timeout: 300